//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRole
    {
        public AdminRole()
        {
            this.Admins = new HashSet<Admin>();
            this.AdminRoleAccesses = new HashSet<AdminRoleAccess>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<AdminRoleAccess> AdminRoleAccesses { get; set; }
    }
}
