//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRoleAccess
    {
        public int adminrole_id { get; set; }
        public int module_id { get; set; }
        public Nullable<bool> is_viewable { get; set; }
        public Nullable<bool> is_editable { get; set; }
        public Nullable<bool> is_addable { get; set; }
        public Nullable<bool> is_deleteable { get; set; }
    
        public virtual AdminModule AdminModule { get; set; }
        public virtual AdminRole AdminRole { get; set; }
    }
}
