//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.InventoryItems = new HashSet<InventoryItem>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public string last_action { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
        public virtual AdminRole AdminRole { get; set; }
    }
}
