//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIKey
    {
        public string unique_id { get; set; }
        public string token { get; set; }
        public string token_salt { get; set; }
        public Nullable<System.DateTime> token_expire { get; set; }
        public string os { get; set; }
        public string os_version { get; set; }
        public string model { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<int> flag_debug { get; set; }
        public string token_old { get; set; }
        public Nullable<System.DateTime> token_old_expire { get; set; }
        public string gcm_device_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
