//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallbackMOLLog
    {
        public int id { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public string nbcb { get; set; }
        public string tranID { get; set; }
        public string orderid { get; set; }
        public string status { get; set; }
        public string domain { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public string appcode { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public string skey { get; set; }
        public string channel { get; set; }
        public string error_code { get; set; }
        public string error_desc { get; set; }
    }
}
