//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.CampaignImages = new HashSet<CampaignImage>();
            this.CampaignHistories = new HashSet<CampaignHistory>();
            this.CampaignPrimaryTags = new HashSet<CampaignPrimaryTag>();
            this.CampaignSecondaryTags = new HashSet<CampaignSecondaryTag>();
            this.CampaignRules = new HashSet<CampaignRule>();
        }
    
        public int id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_action { get; set; }
        public string LINK_URL { get; set; }
    
        public virtual Merchant Merchant { get; set; }
        public virtual ICollection<CampaignImage> CampaignImages { get; set; }
        public virtual ICollection<CampaignHistory> CampaignHistories { get; set; }
        public virtual ICollection<CampaignPrimaryTag> CampaignPrimaryTags { get; set; }
        public virtual ICollection<CampaignSecondaryTag> CampaignSecondaryTags { get; set; }
        public virtual ICollection<CampaignRule> CampaignRules { get; set; }
    }
}
