//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignRule
    {
        public int id { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> numberofviews { get; set; }
        public Nullable<int> campaign_id { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_action { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<bool> no_end_time { get; set; }
        public Nullable<bool> monday { get; set; }
        public Nullable<bool> tuesday { get; set; }
        public Nullable<bool> wednesday { get; set; }
        public Nullable<bool> thursday { get; set; }
        public Nullable<bool> friday { get; set; }
        public Nullable<bool> saturday { get; set; }
        public Nullable<bool> sunday { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<int> agegroup_start { get; set; }
        public Nullable<int> agegroup_end { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Image Image { get; set; }
    }
}
