//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPrimaryTag
    {
        public int campaign_id { get; set; }
        public int tag_id { get; set; }
        public string last_action { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
