//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.InventoryItems = new HashSet<InventoryItem>();
            this.Merchants = new HashSet<Merchant>();
            this.Branches = new HashSet<Branch>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public string last_action { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
