//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook
    {
        public long id { get; set; }
        public string facebookid { get; set; }
        public Nullable<int> user_id { get; set; }
        public string accesstoken { get; set; }
        public Nullable<System.DateTime> link_date { get; set; }
    
        public virtual User User { get; set; }
    }
}
