//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameTransaction
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<double> hidden_latitude { get; set; }
        public Nullable<double> hidden_longitude { get; set; }
        public Nullable<int> timeused { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string last_action { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
    }
}
