//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Users = new HashSet<User>();
            this.CampaignRules = new HashSet<CampaignRule>();
        }
    
        public int id { get; set; }
        public string url { get; set; }
        public string last_action { get; set; }
        public Nullable<int> size_in_bit { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string checksum { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<CampaignRule> CampaignRules { get; set; }
    }
}
