//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPointTrxD
    {
        public int id { get; set; }
        public Nullable<int> kpointh_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> action_type { get; set; }
        public Nullable<int> from_user { get; set; }
        public Nullable<int> to_user { get; set; }
        public string remarks { get; set; }
        public Nullable<int> inventoryitem_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
    
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual KPointTrxH KPointTrxH { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
