//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPointTrxH
    {
        public KPointTrxH()
        {
            this.KPointTrxDs = new HashSet<KPointTrxD>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_action { get; set; }
    
        public virtual ICollection<KPointTrxD> KPointTrxDs { get; set; }
        public virtual User User { get; set; }
    }
}
