//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileLog
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string url { get; set; }
        public string activity { get; set; }
        public string ip_address { get; set; }
        public string unique_id { get; set; }
        public string request { get; set; }
        public string response { get; set; }
    }
}
