//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.PromotionTrxes = new HashSet<PromotionTrx>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_action { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<bool> flag_on_schedule { get; set; }
    
        public virtual ICollection<PromotionTrx> PromotionTrxes { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
