//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionStatu
    {
        public RedemptionStatu()
        {
            this.Redemptions = new HashSet<Redemption>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Redemption> Redemptions { get; set; }
    }
}
