//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardImage
    {
        public int image_id { get; set; }
        public Nullable<bool> main { get; set; }
        public int reward_id { get; set; }
    
        public virtual Reward Reward { get; set; }
    }
}
