//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardCriteria
    {
        public RewardCriteria()
        {
            this.Rewards = new HashSet<Reward>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Reward> Rewards { get; set; }
    }
}
