//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public Reward()
        {
            this.RewardImages = new HashSet<RewardImage>();
            this.Redemptions = new HashSet<Redemption>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string sponsor_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public string terms { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string group_name { get; set; }
        public Nullable<decimal> total_revenue { get; set; }
        public Nullable<decimal> cal_total_revenue { get; set; }
        public Nullable<int> game_type { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_action { get; set; }
        public Nullable<decimal> fake_visualmeter { get; set; }
        public Nullable<bool> freedeal { get; set; }
        public Nullable<int> criteria_id { get; set; }
        public Nullable<int> reward_type_id { get; set; }
        public Nullable<int> point_requirement { get; set; }
        public string sub_title { get; set; }
        public Nullable<bool> flag_one_time { get; set; }
        public Nullable<int> number_of_stock { get; set; }
    
        public virtual RewardCriteria RewardCriteria { get; set; }
        public virtual ICollection<RewardImage> RewardImages { get; set; }
        public virtual RewardType RewardType { get; set; }
        public virtual ICollection<Redemption> Redemptions { get; set; }
    }
}
