//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.CampaignPrimaryTags = new HashSet<CampaignPrimaryTag>();
            this.CampaignSecondaryTags = new HashSet<CampaignSecondaryTag>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string last_action { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual ICollection<CampaignPrimaryTag> CampaignPrimaryTags { get; set; }
        public virtual ICollection<CampaignSecondaryTag> CampaignSecondaryTags { get; set; }
    }
}
