//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adz.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BillingUsers = new HashSet<BillingUser>();
            this.Facebooks = new HashSet<Facebook>();
            this.GameTransactions = new HashSet<GameTransaction>();
            this.KPointTrxHs = new HashSet<KPointTrxH>();
            this.ShippingUsers = new HashSet<ShippingUser>();
            this.TransactionFreeDeals = new HashSet<TransactionFreeDeal>();
            this.Transactions = new HashSet<Transaction>();
            this.Winners = new HashSet<Winner>();
            this.WishLists = new HashSet<WishList>();
            this.APIKeys = new HashSet<APIKey>();
            this.CampaignHistories = new HashSet<CampaignHistory>();
            this.Redemptions = new HashSet<Redemption>();
            this.PromotionTrxes = new HashSet<PromotionTrx>();
            this.UserTrxes = new HashSet<UserTrx>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<System.DateTime> last_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<System.DateTime> last_lockout { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public Nullable<int> userstatus_id { get; set; }
        public Nullable<bool> notif { get; set; }
        public Nullable<bool> locked_status { get; set; }
        public string resetpass { get; set; }
        public Nullable<System.DateTime> resetpass_expire { get; set; }
        public Nullable<int> point_balance { get; set; }
        public string referral_code { get; set; }
        public string referred_by { get; set; }
        public string facebook_id { get; set; }
        public string contact_number { get; set; }
    
        public virtual ICollection<BillingUser> BillingUsers { get; set; }
        public virtual ICollection<Facebook> Facebooks { get; set; }
        public virtual ICollection<GameTransaction> GameTransactions { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<KPointTrxH> KPointTrxHs { get; set; }
        public virtual ICollection<ShippingUser> ShippingUsers { get; set; }
        public virtual ICollection<TransactionFreeDeal> TransactionFreeDeals { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual UserStatu UserStatu { get; set; }
        public virtual ICollection<Winner> Winners { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
        public virtual ICollection<APIKey> APIKeys { get; set; }
        public virtual ICollection<CampaignHistory> CampaignHistories { get; set; }
        public virtual ICollection<Redemption> Redemptions { get; set; }
        public virtual ICollection<PromotionTrx> PromotionTrxes { get; set; }
        public virtual ICollection<UserTrx> UserTrxes { get; set; }
    }
}
